config/routes.rb
Rails.application.routes.draw do
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [ :index, :show, :destroy ]
  resource  :password, only: [ :edit, :update ]
  namespace :identity do
    resource :email,              only: [ :edit, :update ]
    resource :email_verification, only: [ :show, :create ]
    resource :password_reset,     only: [ :new, :edit, :create, :update ]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "dashboard#show"

  resource :dashboard, only: [ :show ]
  resources :projects do
    resources :boards do
      resources :cards, only: [ :show, :new, :create, :edit, :update ]
      resources :columns, only: [ :show ], controller: 'boards/columns'
      resources :board_columns # Is this for adding and remove columns from a board?
    end
    resources :columns
  end
  resources :board_columns, only: [:update]

  resources :actions, only: [ :index ]
  resources :cards, only: [ :update ]
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :boards
  has_many :columns
  
  validates :name, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def show
    @project = Project.find(params[:id])
    @boards = @project.boards
    @columns = @project.columns
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to root_path, notice: "Project Created"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to root_path, notice: "Project Updated"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def project_params
    params.require(:project).permit(:name, :description)
  end
end

app/views/projects/_form.html.erb
<%= simple_form_for @project do |form| %>
  <%= form.input :name %>
  <%= form.input :description%>
  
  <%= form.button :submit, "Save Project" %>
<% end %>

app/views/projects/edit.html.erb
<div class="card__background">
  <h1>Edit Project</h1>
  <%= render 'form' %>
</div>

app/views/projects/new.html.erb
<div class="card__background">
  <h1>New Project</h1>
  <%= render 'form' %>
</div>

app/views/projects/show.html.erb
<h2><%= @project.name %></h2>

<%= link_to "Edit Project", edit_project_path(@project.id), class: "button__primary"  %>

<%= link_to "New Board", new_project_board_path(@project), class: "button__primary"  %>

<%= link_to "New Column", new_project_column_path(@project), class: "button__primary"  %>

<% @boards.each do |board| %>
  <%= link_to project_board_path(@project, board), class: "project-card-link" do %>
    <div class="board-card">
      <div><%= board.name %></div>
      <div><%= board.description %></div>
    </div>
  <% end %>
<% end %>