config/routes.rb
Rails.application.routes.draw do
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [ :index, :show, :destroy ]
  resource  :password, only: [ :edit, :update ]
  namespace :identity do
    resource :email,              only: [ :edit, :update ]
    resource :email_verification, only: [ :show, :create ]
    resource :password_reset,     only: [ :new, :edit, :create, :update ]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "dashboard#show"

  resource :dashboard, only: [ :show ]
  resources :projects do
    resources :boards do
      resources :cards, only: [ :show, :new, :create, :edit, :update ]
      resources :columns, only: [ :show ], controller: 'boards/columns'
      resources :board_columns # Is this for adding and remove columns from a board?
    end
    resources :columns
  end
  resources :board_columns, only: [:update]

  resources :actions, only: [ :index ]
  resources :cards, only: [ :update ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include ActionView::RecordIdentifier

  before_action :set_current_request_details
  before_action :authenticate
  before_action :set_cable_client_id

  helper_method :current_user

  def current_user
    Current.session&.user
  end

  private

  def authenticate
    if session_record = Session.find_by_id(cookies.signed[:session_token])
      Current.session = session_record
    else
      redirect_to sign_in_path
    end
  end

  def set_current_request_details
    Current.user_agent = request.user_agent
    Current.ip_address = request.ip
  end

  def close_dialog
    turbo_stream.replace('dialog', partial: 'dialog')
    # turbo_stream.custom_action :close_dialog

  end

  def set_cable_client_id
    @cable_client_id = request.headers["X-Cable-Client-Id"]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def auto_refresh_turbo_frame_tag(dom_id, object:, **attributes, &block)
    data = { 
      controller: "refresh", 
      refresh_cache_key_value: object.cache_key 
    } 

    attributes[:data] = data
    turbo_frame_tag dom_id, **attributes, &block
  end

end

app/views/application/_dialog.html.erb
<dialog id="dialog" class="dialog" data-controller="dialog" data-dialog-open-class="dialog--open">
  <form method="dialog">
    <%= button_tag type: "submit", class: "dialog__close" do %>
      <i class="heroicon-x-mark"></i>
    <% end %>
  </form>
  <%= turbo_frame_tag "dialog_content", data: { dialog_target: 'content' } do %>
    <h1>Dialog</h1>
  <% end %>
</dialog>

app/views/application/_drawer.html.erb
<div class="drawer" data-controller="drawer" data-drawer-open-class="drawer--open">
  <%= button_tag type: "button", class: "drawer__close", data: { controller: "drawer", action: "drawer#close" } do %>
    <i class="heroicon-x-mark"></i>
  <% end %>
  <%= turbo_frame_tag "drawer_content", data: { drawer_target: 'content' } do %>
    <h1>Drawer Content</h1>
  <% end %>
</div>

app/views/application/_html_head.html.erb
  <head>
    <title><%= content_for(:title) || "Brello" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <% if Rails.env.test? %>
      <meta name="turbo-cache-control" content="no-cache">
      <script>
        document.addEventListener("turbo:load", function() {
          Turbo.session.drive = false;
        });
      </script>
    <% end %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">

    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <script src="https://cdn.jsdelivr.net/npm/@shopify/draggable@1.0.0-beta.8/lib/draggable.bundle.js"></script>
    <%= javascript_importmap_tags %>
    <%= turbo_refreshes_with method: :morph %>
  </head>

app/views/application/_project_header.html.erb
<h1><%=@project.name %></h1>

app/views/application/_project_sidebar.html.erb
<div class="sidebar">
  <%= link_to "Boards", project_path(@project) %>
  <%= link_to "Columns", project_columns_path(@project) %>
</div>